* Encoding: UTF-8.

DATASET ACTIVATE DataSet1.
FILTER OFF.
USE ALL.
SELECT IF (Finished = 1).
EXECUTE.

FILTER OFF.
USE ALL.
SELECT IF (Q41 = 2).
EXECUTE.

COMPUTE Humanlike=MEAN(Q11_1,Q11_2,Q11_3,Q11_4).
EXECUTE.

COMPUTE Virtuallike=MEAN(Q14_1,Q14_2,Q14_3,Q14_4).
EXECUTE.

EXAMINE VARIABLES=Humanlike Virtuallike
  /PLOT BOXPLOT STEMLEAF NPPLOT
  /COMPARE GROUPS
  /STATISTICS DESCRIPTIVES
  /CINTERVAL 95
  /MISSING LISTWISE
  /NOTOTAL.


*Nonparametric Tests: Related Samples. 
NPTESTS 
  /RELATED TEST(Humanlike Virtuallike) 
  /MISSING SCOPE=ANALYSIS USERMISSING=EXCLUDE
  /CRITERIA ALPHA=0.05  CILEVEL=95.
NPAR TESTS
  /FRIEDMAN=Q22 Q31 Q35
  /MISSING LISTWISE.

COMPUTE Instagram=MEAN(Q27_1,Q27_2,Q27_3).
EXECUTE.

DESCRIPTIVES VARIABLES=Instagram
  /STATISTICS=MEAN STDDEV MIN MAX.

EXAMINE VARIABLES=Instagram
  /PLOT BOXPLOT STEMLEAF NPPLOT
  /COMPARE GROUPS
  /STATISTICS DESCRIPTIVES
  /CINTERVAL 95
  /MISSING LISTWISE
  /NOTOTAL.
